name: eclash
description: "基于 mihomo 内核的新手友好代理客户端"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.2.0                        # 订阅下载
  path_provider: ^2.1.0               # 获取应用目录
  shared_preferences: ^2.2.0          # 本地存储订阅码等配置
  provider: ^6.1.0                    # 状态管理
  yaml: ^3.1.0                        # 解析配置文件

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/mihomo/
